// vuejs-for-everyone/vue-movie-db/src/components/MovieDetail.vue
<template>
  <transition name="fade">
    <div class="movie-wrapper" :style="styles">
      <div class="movie-info">
        <h1>{{ movie.title }}</h1>
        <h3>Release Date: {{ movie.release_date }}</h3>
        <p>{{ movie.overview }}</p>
      </div>
    </div>
  </transition>
</template>

<script>
const BACKDROP_PATH = 'https://image.tmdb.org/t/p/w1280'
export default {
  data() {
    return {
      movie: {}
    }
  },
  created: function() {
    this.fetchData()
  },
  methods: {
    fetchData: async function() {
      try {
        const res = await fetch(
          `https://api.themoviedb.org/3/movie/${this.$route.params.id}?api_key=887cffaee5e3334740dd2d4520389025`
        )
        const json = await res.json()
        this.movie = json
      } catch (error) {
        console.log(error)
      }
    }
  },
  computed: {
    styles() {
      return {
        'background-image': `url(${BACKDROP_PATH}/${this.movie.backdrop_path})`
      }
    }
  }
}
</script>

<style scoped>
.movie-wrapper {
  position: relative;
  padding-top: 50vh;
  background-size: cover;
}
.movie-info {
  background: white;
  color: #222;
  padding: 2rem 10%;
}

.fade-enter-active,
.fade-leave-active {
  transition: all 0.3s ease;
}
.fade-enter,
.fade-leave-to {
  opacity: 0;
  transform: translateX(100%);
}
</style>

// react-16-for-everyone/lumdb/src/MovieDetail.js
import React, { Component } from 'react'
import styled from 'styled-components'
import Overdrive from 'react-overdrive'
import { Poster } from './Movie'

const API_KEY = '887cffaee5e3334740dd2d4520389025'
const POSTER_PATH = 'https://image.tmdb.org/t/p/w154'
const BACKDROP_PATH = 'https://image.tmdb.org/t/p/w1280'

export default class MovieDetail extends Component {
  constructor(props) {
    super(props)
    this.state = {
      movie: {}
    }
  }

  async componentDidMount() {
    const { params } = this.props.match
    try {
      const res = await fetch(`https://api.themoviedb.org/3/movie/${params.id}?api_key=${API_KEY}`)
      const movie = await res.json()
      this.setState({ movie })
    } catch (error) {
      console.log(error)
    }
  }

  render() {
    const { movie } = this.state
    const { id, title, release_date, overview, poster_path, backdrop_path } = movie
    return (
      <>
        {title && (
          <MovieWrapper backdrop={`${BACKDROP_PATH}${backdrop_path}`}>
            <MovieInfo>
              <Overdrive id={id}>
                <Poster src={`${POSTER_PATH}${poster_path}`} alt={title} />
              </Overdrive>
              <div>
                <h1>{title}</h1>
                <h3>{release_date}</h3>
                <p>{overview}</p>
              </div>
            </MovieInfo>
          </MovieWrapper>
        )}
      </>
    )
  }
}

const MovieWrapper = styled.div`
  position: relative;
  padding-top: 50vh;
  background: url(${props => props.backdrop}) no-repeat;
  background-size: cover;
`

const MovieInfo = styled.div`
  background-color: #fff;
  text-align: left;
  padding: 2rem 10%;
  display: flex;

  > div {
    margin-left: 20px;
  }

  img {
    position: relative;
    top: -5rem;
  }
`
