// react-testing-for-beginners/React-Testing-For-Beginners/src/movies/Movie.js
import React from 'react'
import PropTypes from 'prop-types'
import { Link } from 'react-router-dom'
import styled from 'styled-components'
import Overdrive from 'react-overdrive'

export const POSTER_PATH = 'http://image.tmdb.org/t/p/w154'

const Movie = ({ movie }) => {
  if (!movie) {
    return null
  }

  return (
    <Link to={`/${movie.id}`} data-testid="movie-link">
      <Overdrive id={`${movie.id}`}>
        <Poster
          data-testid="movie-img"
          src={`${POSTER_PATH}${movie.poster_path}`}
          alt={movie.title}
        />
      </Overdrive>
    </Link>
  )
}

export default Movie

Movie.propTypes = {
  movie: PropTypes.shape({
    id: PropTypes.string.isRequired,
    title: PropTypes.string.isRequired,
    poster_path: PropTypes.string.isRequired
  }).isRequired
}

export const Poster = styled.img`
  box-shadow: 0 0 35px black;
`

// vuejs-for-everyone/vue-movie-db/src/components/Movie.vue
<template>
  <router-link :to="moviePath">
    <img :src="posterImage" :alt="movie.title" />
  </router-link>
</template>

<script>
const POSTER_PATH = 'https://image.tmdb.org/t/p/w154'
export default {
  props: ['movie'],
  computed: {
    posterImage: function() {
      return `${POSTER_PATH}/${this.movie.poster_path}`
    },
    moviePath: function() {
      return `/movie/${this.movie.id}`
    }
  }
}
</script>

<style scoped>
img {
  box-shadow: 0 0 35px black;
}
</style>
