// react-testing-for-beginners/React-Testing-For-Beginners/src/movies/MoviesList.js
/* eslint react/no-did-mount-set-state: 0 */
import React, { PureComponent } from 'react'
import styled from 'styled-components'
import Movie from './Movie'

class MoviesList extends PureComponent {
  state = {
    movies: []
  }

  async componentDidMount() {
    try {
      const res = await fetch(
        'https://api.themoviedb.org/3/discover/movie?api_key=hi&language=en-US&sort_by=popularity.desc&include_adult=false&include_video=false&page=1'
      )
      const movies = await res.json()
      this.setState({
        movies: movies.results
      })
    } catch (e) {
      console.log(e)
    }
  }

  render() {
    const { movies } = this.state
    if (!(movies && movies.length > 0)) {
      return <h1 data-testid="loading">Loading...</h1>
    }
    return (
      <MovieGrid>
        {this.state.movies.map(movie => (
          <Movie key={movie.id} movie={movie} />
        ))}
      </MovieGrid>
    )
  }
}

export default MoviesList

const MovieGrid = styled.div`
  display: grid;
  padding: 1rem;
  grid-template-columns: repeat(6, 1fr);
  grid-row-gap: 1rem;
`

// vuejs-for-everyone/vue-movie-db/src/components/MoviesList.vue
<template>
  <ul>
    <li v-for="movie in movies" :key="movie.title">
      <Movie :movie="movie" />
    </li>
  </ul>
</template>

<script>
import Movie from './Movie.vue'
export default {
  name: 'MoviesList',
  data() {
    return {
      movies: []
    }
  },
  beforeCreate() {
    console.log('before Create')
  },
  created() {
    this.fetchData()
  },
  methods: {
    fetchData: async function() {
      try {
        const res = await fetch(
          `https://api.themoviedb.org/3/discover/movie?sort_by=popularity.desc&api_key=887cffaee5e3334740dd2d4520389025`
        )
        const json = await res.json()
        this.movies = json.results
      } catch (error) {
        console.log(error)
      }
    }
  },
  components: {
    Movie
  }
}
</script>

<style scoped>
ul {
  display: grid;
  list-style: none;
  padding: 1rem;
  margin: 0;
  grid-row-gap: 1rem;
  grid-template-columns: repeat(6, 1fr);
}
</style>
